; From environment *report*
(module
  (lambda
    quote
    letrec
    if
    begin
    set!
    define
    *
    +
    -
    /
    <
    <=
    =
    >
    >=
    abs
    acos
    angle
    append
    apply
    asin
    assoc
    assq
    assv
    atan
    boolean?
    call-with-current-continuation
    call-with-input-file
    call-with-output-file
    call-with-values
    car
    cdr
    caar
    cadr
    cdar
    cddr
    caaar
    caadr
    cadar
    caddr
    cdaar
    cdadr
    cddar
    cdddr
    caaaar
    caaadr
    caadar
    caaddr
    cadaar
    cadadr
    caddar
    cadddr
    cdaaar
    cdaadr
    cdadar
    cdaddr
    cddaar
    cddadr
    cdddar
    cddddr
    ceiling
    char->integer
    char-alphabetic?
    char-ci<=?
    char-ci<?
    char-ci=?
    char-ci>=?
    char-ci>?
    char-downcase
    char-lower-case?
    char-numeric?
    char-ready?
    char-upcase
    char-upper-case?
    char-whitespace?
    char<=?
    char<?
    char=?
    char>=?
    char>?
    char?
    close-input-port
    close-output-port
    complex?
    cons
    cos
    current-input-port
    current-output-port
    denominator
    display
    dynamic-wind
    eof-object?
    eq?
    equal?
    eqv?
    eval
    even?
    exact->inexact
    exact?
    exp
    expt
    floor
    for-each
    force
    gcd
    imag-part
    inexact->exact
    inexact?
    input-port?
    integer->char
    integer?
    interaction-environment
    lcm
    length
    list
    list->string
    list->vector
    list-ref
    list-tail
    list?
    load
    log
    magnitude
    make-polar
    make-rectangular
    make-string
    make-vector
    map
    max
    member
    memq
    memv
    min
    modulo
    negative?
    newline
    not
    null-environment
    null?
    number->string
    number?
    numerator
    odd?
    open-input-file
    open-output-file
    output-port?
    pair?
    peek-char
    positive?
    procedure?
    quotient
    rational?
    rationalize
    read
    read-char
    real-part
    real?
    remainder
    reverse
    round
    scheme-report-environment
    set-car!
    set-cdr!
    sin
    sqrt
    string
    string->list
    string->number
    string->symbol
    string-append
    string-ci<=?
    string-ci<?
    string-ci=?
    string-ci>=?
    string-ci>?
    string-copy
    string-fill!
    string-length
    string-ref
    string-set!
    string<=?
    string<?
    string=?
    string>=?
    string>?
    string?
    substring
    symbol->string
    symbol?
    tan
    truncate
    values
    vector
    vector->list
    vector-fill!
    vector-length
    vector-ref
    vector-set!
    vector?
    with-input-from-file
    with-output-to-file
    write
    write-char
    zero?))

; From environment *toplevel-lib*
(module
  (_expression-type
    _gcd
    _integer?
    _lcm
    _make-config-parameter
    _make-native-parameter
    _make-parameter
    _signal-hook!
    _signal-unhook!
    _with-environment
    absolute-path?
    annotate
    annotation
    annotation-expression
    annotation-keys
    annotation-source
    annotation-stripped
    annotation?
    ashl
    ashr
    box
    box?
    call-with-escape-continuation
    call-with-failure-continuation
    circular?
    class-path-extension
    class-path-extension-append!
    compact-string-rep
    compile
    cons-immutable
    current-wind
    environment?
    file-exists?
    find-last-unique-vector-element
    find-resource
    find-resources
    flush-output-port
    gensym
    gensym?
    get-output-string
    get-sidecar-environment
    get-symbolic-environment
    getenv
    getprop
    hash-code
    immutable-pair?
    immutable-vector?
    input-port-location
    intern
    load-expanded
    load-native-library
    make-annotation
    make-child-environment
    make-immutable-vector
    max-float-precision
    min-float-precision
    native-library-binding
    native-library-binding-names
    native-library-name
    native-library-version
    normalize-url
    open-autoflush-binary-output-port
    open-autoflush-character-output-port
    open-buffered-character-input-port
    open-buffered-character-output-port
    open-character-input-port
    open-character-output-port
    open-input-string
    open-output-string
    open-source-input-file
    open-source-input-string
    parameter?
    parent-environment
    peek-byte
    permit-interrupts
    port?
    program
    putprop
    read-byte
    read-code
    read-string
    remprop
    seal-immutable-pair!
    seal-immutable-vector!
    set-annotation!
    set-annotation-stripped!
    set-box!
    set-symbolic-environment!
    sisc-initial-environment
    sleep
    string->uninterned-symbol
    string-input-port?
    string-output-port?
    syntactic-token->string
    syntactic-token?
    system-time
    time-zone-offset
    unbox
    unknown
    void
    void?
    with-failure-continuation
    write-byte
    write-string))
